[tool.poetry]
name = "keras-konverter"
version = "0.1.0"
description = "A tool to convert simple Keras models to pure Python + NumPy"
authors = ["Shane Smiskol <shane@smiskol.com>"]
license = "MIT"

packages = [
    { include = "konverter" }
]

[tool.poetry.dependencies]
python = "^3.6"
tensorflow = "^2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
