# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Konverter Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.6
        poetry_version: 1.0.5
        args: install

    - name: Test model outputs
      run: |
        cd tests
        ls -lah
        python -V
        python3 -V
        python3 test_konverter.py
